import type { Profile } from "@/domain/profile";

const daysFromNow = (now: Date, days: number) =>
  new Date(now.getTime() + days * 86_400_000).toISOString();

const daysAgo = (now: Date, days: number) =>
  new Date(now.getTime() - days * 86_400_000).toISOString();

/**
 * Fictional clients for a bridal makeup business.
 *
 * Wedding dates are deliberately spread relative to "now" so every countdown
 * trigger has someone it applies to: one bride just past her three-month mark,
 * one inside the final week, one the night before, and two whose weddings have
 * already happened and are due feedback or a re-booking nudge.
 */
export function seedProfiles(now: Date): Profile[] {
  return [
    {
      id: "prof_sophie_bennett",
      customerId: "cli_1041",
      firstName: "Sophie",
      lastName: "Bennett",
      email: "sophie.bennett@example.test",
      mobile: "+44 7700 900101",
      country: "United Kingdom",
      loyaltyTier: "Gold",
      appInstalled: false,
      lifetimeValue: 720,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["bride", "confirmed"],
      createdAt: daysAgo(now, 210),
      engagementScore: 78,
      messagesInLast24h: 0,
      messagesInLast7d: 1,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "subscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        // 91 days out — just past the three-month reminder.
        weddingDate: daysFromNow(now, 91),
        venue: "Hedingham Barn",
        serviceBooked: "Bridal makeup + 3 bridesmaids",
        partySize: 4,
        trialCompleted: true,
        readyByTime: "11:30",
        depositPaid: true,
        referredBy: "Instagram",
      },
      segmentNote: "Three months out — the skincare prep reminder is due.",
    },
    {
      id: "prof_amara_okafor",
      customerId: "cli_1042",
      firstName: "Amara",
      lastName: "Okafor",
      email: "amara.okafor@example.test",
      mobile: "+44 7700 900102",
      country: "United Kingdom",
      loyaltyTier: "Gold",
      appInstalled: false,
      lifetimeValue: 890,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["bride", "confirmed"],
      createdAt: daysAgo(now, 300),
      engagementScore: 84,
      messagesInLast24h: 0,
      messagesInLast7d: 2,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "subscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        // Inside the final week.
        weddingDate: daysFromNow(now, 6),
        venue: "The Old Rectory",
        serviceBooked: "Bridal makeup + 5 bridesmaids + mothers",
        partySize: 8,
        trialCompleted: true,
        readyByTime: "10:00",
        depositPaid: true,
        referredBy: "Word of mouth",
      },
      segmentNote: "One week to go — final details message is due.",
    },
    {
      id: "prof_hannah_price",
      customerId: "cli_1043",
      firstName: "Hannah",
      lastName: "Price",
      email: "hannah.price@example.test",
      mobile: "+44 7700 900103",
      country: "United Kingdom",
      loyaltyTier: "Silver",
      appInstalled: false,
      lifetimeValue: 450,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["bride", "confirmed"],
      createdAt: daysAgo(now, 420),
      engagementScore: 66,
      messagesInLast24h: 1,
      messagesInLast7d: 3,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "subscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        // Getting married tomorrow.
        weddingDate: daysFromNow(now, 1),
        venue: "Ashcombe Hall",
        serviceBooked: "Bridal makeup only",
        partySize: 1,
        trialCompleted: true,
        readyByTime: "09:30",
        depositPaid: true,
        referredBy: "Venue recommendation",
      },
      segmentNote: "Wedding is tomorrow — the night-before message is due.",
    },
    {
      id: "prof_grace_donnelly",
      customerId: "cli_1044",
      firstName: "Grace",
      lastName: "Donnelly",
      email: "grace.donnelly@example.test",
      mobile: "+44 7700 900104",
      country: "United Kingdom",
      loyaltyTier: "Gold",
      appInstalled: false,
      lifetimeValue: 640,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["bride", "past-bride"],
      createdAt: daysAgo(now, 500),
      engagementScore: 71,
      messagesInLast24h: 0,
      messagesInLast7d: 0,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "subscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        // Married six weeks ago — feedback request is due.
        weddingDate: daysFromNow(now, -43),
        venue: "Thornbury Manor",
        serviceBooked: "Bridal makeup + 2 bridesmaids",
        partySize: 3,
        trialCompleted: true,
        readyByTime: "10:30",
        depositPaid: true,
        referredBy: "Instagram",
      },
      segmentNote: "Married six weeks ago — feedback request is due.",
    },
    {
      id: "prof_lucy_chen",
      customerId: "cli_1045",
      firstName: "Lucy",
      lastName: "Chen",
      email: "lucy.chen@example.test",
      mobile: "+44 7700 900105",
      country: "United Kingdom",
      loyaltyTier: "Silver",
      appInstalled: false,
      lifetimeValue: 520,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["bride", "past-bride"],
      createdAt: daysAgo(now, 700),
      engagementScore: 52,
      messagesInLast24h: 0,
      messagesInLast7d: 0,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "unsubscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        weddingDate: daysFromNow(now, -200),
        venue: "Fairlight House",
        serviceBooked: "Bridal makeup + 4 bridesmaids",
        partySize: 5,
        trialCompleted: true,
        readyByTime: "11:00",
        depositPaid: true,
        referredBy: "Google",
      },
      segmentNote: "Past bride, SMS opted out — email-only for the occasion-makeup offer.",
    },
    {
      id: "prof_niamh_gallagher",
      customerId: "cli_1046",
      firstName: "Niamh",
      lastName: "Gallagher",
      email: "niamh.gallagher@example.test",
      mobile: "+353 87 900106",
      country: "Ireland",
      loyaltyTier: "Bronze",
      appInstalled: false,
      lifetimeValue: 0,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["enquiry"],
      createdAt: daysAgo(now, 9),
      engagementScore: 44,
      messagesInLast24h: 0,
      messagesInLast7d: 0,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "unknown",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        // Enquiry only — the countdown triggers must skip her.
        bookingStatus: "enquiry",
        weddingDate: daysFromNow(now, 120),
        venue: "Undecided",
        serviceBooked: "—",
        partySize: 0,
        trialCompleted: false,
        readyByTime: "",
        depositPaid: false,
        referredBy: "Website form",
      },
      segmentNote: "Enquiry, not booked — countdown triggers skip her until confirmed.",
    },
    {
      id: "prof_ruth_maguire",
      customerId: "cli_1047",
      firstName: "Ruth",
      lastName: "Maguire",
      email: "ruth.maguire@example.test",
      mobile: "+44 7700 900107",
      country: "United Kingdom",
      loyaltyTier: "Bronze",
      appInstalled: false,
      lifetimeValue: 180,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["occasion"],
      createdAt: daysAgo(now, 60),
      engagementScore: 35,
      messagesInLast24h: 0,
      messagesInLast7d: 4,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "subscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        weddingDate: null,
        venue: "—",
        serviceBooked: "Occasion makeup",
        partySize: 1,
        trialCompleted: false,
        readyByTime: "",
        depositPaid: true,
        referredBy: "Instagram",
      },
      segmentNote: "Occasion client with no wedding date — countdown triggers have no anchor.",
    },
    {
      id: "prof_beatrice_hall",
      customerId: "cli_1048",
      firstName: "Beatrice",
      lastName: "Hall",
      email: "beatrice.hall@example.test",
      mobile: "+44 7700 900108",
      country: "United Kingdom",
      loyaltyTier: "Platinum",
      appInstalled: false,
      lifetimeValue: 1480,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["bride", "confirmed", "vip"],
      createdAt: daysAgo(now, 150),
      engagementScore: 91,
      messagesInLast24h: 0,
      messagesInLast7d: 1,
      contactability: {
        email: "subscribed",
        push: "unknown",
        sms: "subscribed",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "confirmed",
        // Also on the three-month mark, but a much larger party.
        weddingDate: daysFromNow(now, 92),
        venue: "Combe Abbey",
        serviceBooked: "Bridal makeup + 6 bridesmaids + 2 mothers",
        partySize: 9,
        trialCompleted: false,
        readyByTime: "09:00",
        depositPaid: true,
        referredBy: "Wedding fair",
      },
      segmentNote: "High-value booking, trial not yet done — three-month reminder is due.",
    },
    {
      id: "prof_erin_walsh",
      customerId: "cli_1049",
      firstName: "Erin",
      lastName: "Walsh",
      email: "erin.walsh@example.test",
      mobile: "+44 7700 900109",
      country: "United Kingdom",
      loyaltyTier: "Bronze",
      appInstalled: false,
      lifetimeValue: 0,
      preferredLanguage: "English",
      preferredClub: "—",
      tags: ["enquiry"],
      createdAt: daysAgo(now, 2),
      engagementScore: 20,
      messagesInLast24h: 0,
      messagesInLast7d: 0,
      contactability: {
        email: "unsubscribed",
        push: "unknown",
        sms: "unknown",
        globallySuppressed: false,
        hasPushToken: false,
      },
      attributes: {
        bookingStatus: "enquiry",
        weddingDate: daysFromNow(now, 400),
        venue: "Undecided",
        serviceBooked: "—",
        partySize: 0,
        trialCompleted: false,
        readyByTime: "",
        depositPaid: false,
        referredBy: "Website form",
      },
      segmentNote: "Enquiry who opted out of email — nothing may be sent to her.",
    },
  ];
}
